/**
 * The tiny shell behind the cookie CLI prompt.
 *
 * The panel has always *looked* like a terminal. This makes it behave like
 * one for anyone who tries: `ls` lists a small fake filesystem, `cat` reads
 * the files, and one of them is executable. Finding `game.exe` is the point;
 * everything else exists so that finding it feels earned rather than
 * announced.
 *
 * Ported from the kit specimen at preview/cookie-cli.html.
 *
 * Pure: commands take state and return output plus an optional effect, so
 * the React component decides what actually happens. That keeps consent
 * behaviour out of a file about pretending to be bash.
 */

export const FS_FILES = [
  {name: 'README.md',    type: 'file', size: 421,  exec: false},
  {name: 'cookies.toml', type: 'file', size: 847,  exec: false},
  {name: 'game.exe',     type: 'file', size: 6320, exec: true},
  {name: 'index.html',   type: 'file', size: 312,  exec: false},
  {name: 'preferences',  type: 'dir',  size: 64,   exec: false},
  {name: 'privacy.md',   type: 'file', size: 198,  exec: false},
  {name: 'snake.txt',    type: 'file', size: 142,  exec: false},
  {name: '.config',      type: 'dir',  size: 64,   exec: false, hidden: true},
  {name: '.bashrc',      type: 'file', size: 88,   exec: false, hidden: true},
];

const FILE_CONTENTS = {
  'README.md': `# conduction.nl

This is the company website. We use cookies for:
  - essential functions (always on)
  - aggregate analytics
  - your preferences

Pick what you're OK with above. Or hit a number key.

PS: there's a game.exe in here somewhere if you're bored.
    Try \`ls\` to find it.`,

  'cookies.toml': `# cookies.toml — generated by cookie-consent
# https://conduction.nl/privacy

[essential]
required = true
description = "Session, CSRF token, language preference."

[analytics]
required = false
description = "Aggregate, anonymous."

[preferences]
required = false
description = "Theme, language, collapsed docs sections."`,

  'privacy.md': `# privacy

We do not sell, share, or rent your data.
The full policy lives at /privacy.`,

  'snake.txt': `snake.exe was removed in v2.
Management felt one game was enough.
Management was wrong, but game.exe survived.`,

  '.bashrc': `# nothing interesting here. we checked.
alias ll='ls -la'`,

  'index.html': `<!doctype html>
<!-- you are, in a sense, already here -->`,
};

const HELP = `Available commands:
  ls [-a]        list files
  cat <file>     print a file
  pwd            print working directory
  whoami         you tell us
  help           this
  clear          clear the scrollback
  ./game.exe     ...try it

Number keys toggle cookie options. [A] accept all, [R] reject non-essential.`;

function pad(s, n) {
  const str = String(s);
  return str + ' '.repeat(Math.max(0, n - str.length));
}

/**
 * Run one command line.
 *
 * @returns {{lines: Array<{text: string, tone?: string}>, effect?: string, clear?: boolean}}
 *          `effect` is 'game' (launch) or 'exit'; the caller performs it.
 */
export function runCommand(raw) {
  const input = raw.trim();
  if (!input) return {lines: []};

  const [cmd, ...args] = input.split(/\s+/);
  const arg = args.filter((a) => !a.startsWith('-')).join(' ');
  const flags = args.filter((a) => a.startsWith('-')).join('');

  switch (cmd) {
    case 'ls': {
      const showAll = flags.includes('a');
      const files = FS_FILES.filter((f) => showAll || !f.hidden);
      return {
        lines: files.map((f) => ({
          text: `${pad(f.type === 'dir' ? 'drwxr-xr-x' : f.exec ? '-rwxr-xr-x' : '-rw-r--r--', 12)}${pad(f.size, 7)}${f.name}${f.type === 'dir' ? '/' : ''}`,
          tone: f.exec ? 'ok' : f.type === 'dir' ? 'dir' : undefined,
        })),
      };
    }

    case 'cat': {
      if (!arg) return {lines: [{text: 'cat: missing operand', tone: 'warn'}]};
      const key = arg.replace(/^\.\//, '');
      if (key === 'game.exe') {
        return {lines: [{text: 'cat: game.exe: binary file. try ./game.exe instead.', tone: 'warn'}]};
      }
      const body = FILE_CONTENTS[key];
      if (body === undefined) {
        const known = FS_FILES.some((f) => f.name === key);
        return {lines: [{text: known ? `cat: ${key}: Is a directory` : `cat: ${key}: No such file or directory`, tone: 'warn'}]};
      }
      return {lines: body.split('\n').map((text) => ({text}))};
    }

    case 'pwd':
      return {lines: [{text: '/home/you'}]};

    case 'whoami':
      return {lines: [{text: 'you, presumably. we did not set a tracking cookie to find out.', tone: 'cmt'}]};

    case 'help':
    case '--help':
    case 'man':
      return {lines: HELP.split('\n').map((text) => ({text}))};

    case 'clear':
      return {lines: [], clear: true};

    case 'exit':
    case 'quit':
      return {lines: [{text: '# there is no exit. pick your cookies.', tone: 'cmt'}], effect: 'exit'};

    case 'game.exe':
    case './game.exe':
    case 'game':
      return {lines: [], effect: 'game'};

    case 'sudo':
      return {lines: [{text: 'you are not in the sudoers file. this incident will not be logged, we do not log.', tone: 'warn'}]};

    case 'rm':
      return {lines: [{text: 'rm: permission denied. the cookies stay until you choose.', tone: 'warn'}]};

    default:
      return {lines: [{text: `${cmd}: command not found. try \`help\`.`, tone: 'warn'}]};
  }
}
