/**
 * Sidebars are auto-generated from the docs/ folder structure.
 * Override here when we want explicit ordering or grouping.
 */
module.exports = {
  docsSidebar: [{ type: 'autogenerated', dirName: '.' }],
};
